### ISSUE TITLE
[Add] sa zobrazuje aj pri otvorenom hárku alebo súbore

### ISSUE THREAD

**Issue by crnkjck** [NikolajKn/bachelor#2]
[Add] sa zobrazuje aj pri otvorenom hárku alebo súbore a funguje vtedy zmätočne.

Tiež by bolo lepšie hovoriť [Add worksheet] na tlačidle aj v nadpise dialógu.

**Comment by NikolajKn** [comment]
[Add] premenované na [Add worksheet] pre tlačidlo aj nadpis dialógového okna a zobrazuje sa iba ak nie je otvorený súbor ani hárok.
